name: yarn jest
on: push

jobs:
  build:
    name: yarn jest
    # latest version of Ubuntu
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      # official Checkout action:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # official setup-node action:
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn --frozen-lockfile
      - run: yarn jest
